config/routes.rb
Rails.application.routes.draw do
  get 'memos/index'
	root 'home#index'
	get 'sessions/new'
	
	get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'

	resources :users
	get 'favorites/index', to: 'favorites#index'
	get 'recipes/published', to: 'recipes#published'
	get 'recipes/from_draft', to: 'recipes#from_draft'
	resources :recipes do 
		resource :favorites, only: [:create, :destroy]
		resource :memos, only: [:create]		
		collection do
			get 'search'
		end
	end

	resources :ingredients do
		get :autocomplete_ingredient_name, on: :collection
	end
	
	resources :diets
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    
    has_many :recipe_categories
    has_many :recipes, through: :recipe_categories
    
    has_many :category_diets
    has_many :diets, through: :category_diets
    accepts_nested_attributes_for :category_diets, allow_destroy: true
    
    # CSV.foreach('db/category_data.csv') do |row|
    #     Category.create(:id => row[0], :name => row[1])
    # end
end

app/models/category_diet.rb
class CategoryDiet < ApplicationRecord
    
    belongs_to :category
    belongs_to :diet
end

app/models/check.rb
class Check < ApplicationRecord

	belongs_to :user
	belongs_to :recipe

	enum status: { cooked: 0, favorite: 1, not_favorite: 2 }
	validates :status, inclusion: { in: Favorite.statuses.keys }
	
	class << self
	def localed_statuses
		statuses.keys.map do |s|
			[ApplicationController.helpers.t("status.favorite.#{s}"), s]
		end
	end
	end
	
end

app/models/diet.rb
class Diet < ApplicationRecord
    
    has_many :category_diets
    has_many :categories, through: :category_diets
    accepts_nested_attributes_for :category_diets, allow_destroy: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
  
  validates_uniqueness_of :recipe_id, scope: :user_id
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    # #前方一致検索
    # scope :by_name_like, lambda { |name|
    #     where('name LIKE :value', { value: "#{sanitize_sql_like(name)}%"})
    # }
    
    validates :name, presence: true, length: {maximum: 15}
    
    NESTED_ALLOWED_PARAMS = [:id, :_destroy, :name ]
    has_many :recipe_ingredients, dependent: :destroy
    has_many :recipes, through: :recipe_ingredients
    
    # #uniqueエラーでた。最初のみ使える?
    # #csvファイルを扱うためのgemを読み込む
    # CSV.foreach('db/ingredient_data.csv') do |row|
    # #foreachは、ファイル（hoge.csv）の各行を引数として、ブロック(do~endまでを範囲とする『引数のかたまり』)を繰り返し実行する
    # #rowには、読み込まれた行が代入される
    #     Ingredient.create(:id => row[0], :name => row[1])
    #     #usersテーブルの各カラムに、各行のn番目の値を代入している。
    # end
end

app/models/memo.rb
class Memo < ApplicationRecord
    
    belongs_to :user
	belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    
    mount_uploader :recipe_image, RecipeImageUploader
    
    ALLOWED_PARAMS = [:title, :user_id, :recipe_image, :status, {category_ids: []}, {ingredient_ids: []}]
   
    validates :title, presence: true, length: {maximum: 20}
    
    enum status: { draft: 0, published: 1 }
    validates :status, inclusion: { in: Recipe.statuses.keys }
    

    belongs_to :user
    
    has_many :recipe_ingredients
    has_many :ingredients, through: :recipe_ingredients, dependent: :destroy
    accepts_nested_attributes_for :recipe_ingredients, allow_destroy: true
    # accepts_nested_attributes_for :ingredients
    
    has_many :recipe_categories
    has_many :categories, through: :recipe_categories, dependent: :destroy
    accepts_nested_attributes_for :recipe_categories, allow_destroy: true
    # accepts_nested_attributes_for :categories
    
    has_many :steps
    accepts_nested_attributes_for :steps, allow_destroy: true
    
    has_many :favorites
    has_many :favorite_users, through: :favorites, source: 'user', dependent: :destroy
    
    has_many :memos
    has_many :memo_users, through: :memos, source: 'user', dependent: :destroy
    
end

app/models/recipe_category.rb
class RecipeCategory < ApplicationRecord
	belongs_to :recipe
	belongs_to :category
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
    
    NESTED_ALLOWED_PARAMS = [ :id, :_destroy, :quantity, :recipe_id, :ingredient_id, ingredient_attributes: Ingredient::NESTED_ALLOWED_PARAMS ]
    
    # has_many :recipes
    # has_many :ingredients
    belongs_to :recipe
    belongs_to :ingredient
end

app/models/step.rb
class Step < ApplicationRecord
    NESTED_ALLOWED_PARAMS = [:id, :_destroy, :recipe_id, :step]
    
    validates :step, presence: true, length: {maximum: 30}
    belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
    
    #emailが~@~.~の正規表示
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    
    #passwordが半角英数字最低1文字以上、かつ、8文字以上12文字以下の正規表示
    VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,12}+\z/i
    
    has_secure_password
    validates :name, presence: true, length: {maximum: 15}
    validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}
    validates :password, presence: true, format: {with: VALID_PASSWORD_REGEX}
    
    has_many :recipes
    
    has_many :favorites
    has_many :favorite_recipes, through: :favorites, source: 'recipe'
    
    has_many :memos
    has_many :memo_recipes, through: :memos, source: 'recipe'
    
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	before_action :authenticate_user
	before_action :set_recipe, only: [:create, :destroy]
	
	def create
		if @recipe.user_id != current_user.id
			@favorite = @recipe.favorites.new(user_id: current_user.id)
		# binding.pry
			if @favorite.save
				redirect_to recipe_url(@recipe), success: "お気に入りに登録"
			else
				redirect_to recipe_url(@recipe), danger: "お気に入りに登録に失敗しました"
			end
		end
	end
	
	def destroy
		@favorite = Favorite.find_by(user_id: current_user.id)
		@favorite.destroy
		redirect_to recipe_url(@recipe), success: "お気に入りから解除"
	end
	
	
	def index
		@favorite_recipes = current_user.favorite_recipes
	end
	
	private
	
	def set_recipe
		@recipe = Recipe.find(params[:recipe_id])
	end
	
	def favorite_params
		params.required(:favorite).merge(user_id: current_user.id, recipe_id: params[:recipe_id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diets_helper.rb
module DietsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/cooked.html.erb
<div class="nav">
    <%= link_to "Cookcare", recipes_path, class: "title" %>
    <%= form_with(url: search_recipes_path, local: true, method: :get) do |f| %>
        <%= f.submit "Search", class: "new-btn" %>
        <%= f.text_field :search, placeholder: "Search Recipes", class: "search-blank" %>
    <% end %>
</div>
<div class="recipe-wrapper clearfix">
    <div class="side-container">
        <div class="account-section">
            <div class="account-info-section clearfix">
                <%= image_tag "icon.png", class: "create-image" %>
                <div class="name-link"><%= @current_user.name %> </div>
            </div>
            <div class="user-tag-section">
                <%= link_to edit_user_path(@current_user) do %><span class="tag-link">Edit Profile</span><span class="hover">プロフィール編集</span><% end %>
            </div>
        </div>
        <div class="post-recipe-section">
            <div class="recipe-info-section clearfix">
                <%= image_tag "green_pen.png", class: "create-image" %>
                <div class="name-link">Post Recipe</div>
            </div>
            <div class="recipe-tag-section">
                <%= link_to new_recipe_path do %><span class="tag-link">Create NEW</span><span class="hover">新規投稿</span><% end %><br>
                <%= link_to recipes_from_draft_path do %><span class="tag-link">From Draft</span><span class="hover">一時保存から</span><% end %>
            </div>
        </div>
        <div class="list-section">
            <div class="list-info-section clearfix">
                <%= image_tag "green_list.png", class: "list-image" %>
                <div class="name-link">Your Lists</div>
            </div>
            <div class="list-links">
                <%= link_to recipes_published_path do %><span class="list-link">Published</span><span class="hover">投稿済み</span><% end %><br>
                <%= link_to favorites_index_path do %><span class="list-link">Favorites</span><span class="hover">お気に入り</span><% end %><br>
                <%= link_to favorites_cooked_path do %><span class="list-link">Cooked</span><span class="hover">調理済み</span><% end %><br>
            </div>
            
        </div>
        <div class="diet-section clearfix">
                <%= image_tag "green_calendar.png", class: "create-image" %>
                <%= link_to diets_path do %><span class="name-link">Calendar</span><span class="hover">カレンダー</span><% end %><br>
        </div>
    </div>
    <div class="main-container">
        <% @favorite_recipes.each do |recipe| %>
            <% @f_recipes.each do |f_recipe|%>
                <% if recipe.id == f_recipe.recipe_id %>
                    <div class="index-single clearfix">
                        <% if recipe.recipe_image? %>
                            <%= image_tag recipe.recipe_image.url, class: "index-single-image" %>
                        <% else %>
                            <%= image_tag "no_image.jpg", class: "index-single-image" %>
                        <% end %>
                        <div class="index-single-name">
                            <%= link_to recipe.title, recipe_path(recipe), class: "index-single-title" %>
                            <div class="index-single-info clearifix">
                                <div class="index-single-favorite">
                                    <%= "Favorites: " + recipe.favorites.favorite.count.to_s %>
                                </div>
                                <div class="index-single-username">
                                    <%= "By " + recipe.user.name %>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                <% end %>
            <% end %>
        <% end %>
    </div>
</div>

app/views/favorites/index.html.erb
<div class="nav">
    <%= link_to "Cookcare", recipes_path, class: "title" %>
    <%= form_with(url: search_recipes_path, local: true, method: :get) do |f| %>
        <%= f.submit "Search", class: "new-btn" %>
        <%= f.text_field :search, placeholder: "Search Recipes", class: "search-blank" %>
    <% end %>
</div>
<div class="recipe-wrapper clearfix">
    <div class="side-container">
        <%= render template: "layouts/sidecontainer.html.erb" %>
    </div>
    <div class="main-container">
        <% @favorite_recipes.each do |recipe| %>
            <div class="index-single clearfix">
                <% if recipe.recipe_image? %>
                    <%= image_tag recipe.recipe_image.url, class: "index-single-image" %>
                <% else %>
                    <%= image_tag "no_image.jpg", class: "index-single-image" %>
                <% end %>
                <div class="index-single-name">
                    <%= link_to recipe.title, recipe_path(recipe), class: "index-single-title" %>
                    <div class="index-single-info clearifix">
                        <div class="index-single-favorite">
                            <%= "Favorites: " + recipe.favorites.favorite.count.to_s %>
                        </div>
                        <div class="index-single-username">
                            <%= "By " + recipe.user.name %>
                        </div>
                        
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>