config/routes.rb
Rails.application.routes.draw do
  get 'memos/index'
	root 'home#index'
	get 'sessions/new'
	
	get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'

	resources :users
	get 'favorites/index', to: 'favorites#index'
	get 'recipes/published', to: 'recipes#published'
	get 'recipes/from_draft', to: 'recipes#from_draft'
	resources :recipes do 
		resource :favorites, only: [:create, :destroy]
		resource :memos, only: [:create]		
		collection do
			get 'search'
		end
	end

	resources :ingredients do
		get :autocomplete_ingredient_name, on: :collection
	end
	
	resources :diets
	
end

app/models/diet.rb
class Diet < ApplicationRecord
    
    has_many :category_diets
    has_many :categories, through: :category_diets
    accepts_nested_attributes_for :category_diets, allow_destroy: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    
    mount_uploader :recipe_image, RecipeImageUploader
    
    ALLOWED_PARAMS = [:title, :user_id, :recipe_image, :status, {category_ids: []}, {ingredient_ids: []}]
   
    validates :title, presence: true, length: {maximum: 20}
    
    enum status: { draft: 0, published: 1 }
    validates :status, inclusion: { in: Recipe.statuses.keys }
    

    belongs_to :user
    
    has_many :recipe_ingredients
    has_many :ingredients, through: :recipe_ingredients, dependent: :destroy
    accepts_nested_attributes_for :recipe_ingredients, allow_destroy: true
    # accepts_nested_attributes_for :ingredients
    
    has_many :recipe_categories
    has_many :categories, through: :recipe_categories, dependent: :destroy
    accepts_nested_attributes_for :recipe_categories, allow_destroy: true
    # accepts_nested_attributes_for :categories
    
    has_many :steps
    accepts_nested_attributes_for :steps, allow_destroy: true
    
    has_many :favorites
    has_many :favorite_users, through: :favorites, source: 'user', dependent: :destroy
    
    has_many :memos
    has_many :memo_users, through: :memos, source: 'user', dependent: :destroy
    
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	
	before_action :authenticate_user
	
	def index
		@recipes = Recipe.published.order(updated_at: :desc).includes(:user, :favorite_users)
	end
	
	def search
		redirect_to recipes_path if params[:search] == ""
		@array_searches = params[:search].split(/[[:blank:]]+/)
		@recipes = []
		#eachをmapに修正する
		@array_searches.each do |search|  # 分割したキーワードごとに検索
			next if search == "" 
			recipes = Recipe.joins(:ingredients)
			@recipes += recipes.where('ingredients.name LIKE ? ', "%#{search}%").or(recipes.where('title LIKE ?', "%#{search}%"))
			#原則前方一致
		end
		@recipes.uniq!
		# @recipes = Recipe.published.order(created_at: :desc).search(params[:search])
	end
	
	def new
		@recipe = Recipe.new
		@categories = Category.all
		@recipe.steps.build
		@recipe.recipe_ingredients.build
		@recipe.ingredients.build
		# カテゴリーの取得とingredientsの取得　.all
	end
	
	def create
		@recipe = current_user.recipes.new(recipe_params)
		params[:recipe][:recipe_ingredients_attributes].each do |attribute|
			attribute.each_with_index do |ingredient, index|
				next if index == 0
			
				# binding.pry
				@ingredient = Ingredient.find_by(name: ingredient[:ingredient][:name])
				# binding.pry
				if @ingredient.nil?
					@ingredient = Ingredient.new(name: ingredient[:ingredient][:name])
					
					@ingredient.save
				end
				@recipe.recipe_ingredients.build(ingredient: @ingredient, quantity: ingredient[:quantity])
				# @recipe.ingredients << @ingredient
			end
		end
		
		# binding.pry
		# # binding.pry
		# #複数だからidがうまくひきわたせない、update_attributes
		
		if @recipe.save
			redirect_to recipes_path, seccess: "投稿完了"
		else
			flash[:danger] = "投稿失敗"
			render :new
		end
	end
	
	def show
		@recipe = Recipe.find_by(id: params[:id])
		@steps = @recipe.steps
		@categories = Category.all
		@recipe_categories = @recipe.recipe_categories
		@recipe_ingredients = @recipe.recipe_ingredients
		@favorite = Favorite.new
		@favorite_recipe = @recipe.favorites.find_by(user_id: current_user)
		@memo = Memo.new
		@memo_recipe = @recipe.memos.order(updated_at: :desc).find_by(user_id: current_user)
	end
	
	def edit
		@recipe = Recipe.find(params[:id])
		@categories = Category.all
		# binding.pry
	end
	
	def update
		@recipe = Recipe.find(params[:id])
		
		if @recipe.update(recipe_params)
			redirect_to recipe_path(@recipe)
		else
			render :edit
		end
	end
	
	def from_draft
		@recipes = current_user.recipes.draft.order(created_at: :desc)
	end
	
	def published
		@recipes = current_user.recipes.published.order(created_at: :desc)
	end
	
	def destroy
		@recipe = Recipe.find_by(id: params[:id])
		@recipe.destroy
		redirect_to recipes_path, danger: "レシピを削除しました"
	end
	
	private
	def recipe_params
		params.require(:recipe).permit(Recipe::ALLOWED_PARAMS, steps_attributes: Step::NESTED_ALLOWED_PARAMS, recipe_categories_attributes: [:category_id])
	end
	
	def search_recipe_params
		params.fetch(:q, '').permit(:body)
	end
	
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_ingredient_fields.html.erb
<div class="nested-fields">
    <%= f.text_field :name, placeholder: "ingredent", class: "step-blank" %>
    <!--<%= f.collection_select :id, Ingredient.all, :id, :name %>-->
    <!--<%= autocomplete_field_tag 'ingredient[name]', nil,  autocomplete_ingredient_name_ingredients_path, placeholder: "ingredient" %>-->
    <%= link_to_remove_association image_tag("minus_icon.png"), f %>
</div>

app/views/recipes/_recipe_ingredient_fields.html.erb
<div class="nested-fields">
	<%= f.fields_for :ingredient do |ingredient| %>
		<% if f.object.ingredient.nil? %>
		  	<%= ingredient.text_field :name, placeholder: "ingredent", class: "ingredient-blank" %>
		<% else %>
			<%= ingredient.text_field :name, placeholder: "ingredent", class: "ingredient-blank", value: f.object.ingredient.name %>
		<% end %>
	<% end %>
	<%= f.text_field :quantity, placeholder: "quantity", class: "ingredient-blank" %>
	<%= link_to_remove_association image_tag("minus_icon.png"), f %>
</div>

app/views/recipes/_step_fields.html.erb
<div class="nested-fields">
    <%= f.text_field :step, class: "step-blank" %>
    <%= link_to_remove_association image_tag("minus_icon.png"), f %>
</div>

app/views/recipes/edit.html.erb
<body>
    <%= form_for @recipe do |f| %>
        <div class="nav">
            <%= link_to "Cookcare", recipes_path, class: "title" %>
            <%= f.submit "Update", class: "new-btn" %>
            <%= f.select :status, Recipe.statuses.keys.to_a, {}, class: "status-btn" %>
            <%= link_to "Delete", recipe_path(@recipe.id), {method: :delete, class: "recipe-delete-btn"} %>
        </div>
        <div class="recipe-wrapper clearfix">
            <div class="side-container">
                <%= render template: "layouts/sidecontainer.html.erb" %>
            </div>
            <div class="main-container">
                <div class="recipe-section clearfix">
                    <div class="recipe-left-section">
                        <div class="title-box">
                            <p>Title</p>
                            <%= f.text_field :title, class: "title-blank" %>
                        </div>
                        <div class="category-box">
                            <p>Category</p>
                            <div class="category-blank">
                                <%= f.collection_check_boxes :category_ids, Category.all, :id, :name, include_hidden: false do |b| %>
                                    <%= b.label { b.check_box + b.text } %>
                                <% end %>
                            </div>
                        </div>
                        <div class="ingredient-box">
                            <p>Ingredients</p>
                            <%= f.fields_for :recipe_ingredients do |recipe_ingredient| %>
                                <div class="field">
                                    <%= render "recipe_ingredient_fields", f: recipe_ingredient %>
                                </div>
                            <% end %>
                            <div class="links">
                                <%= link_to_add_association "Add Ingredient",f, :recipe_ingredients, class: "ingredient-btn" %>
                            </div>
                        </div>
                    </div>
                    <div class="recipe-right-section">
                        <%= f.file_field :recipe_image, placeholder: "Photos", class: "photo-box" %>
                        
                        <div class="step-box">
                            <p>Steps</p>
                            <%= f.fields_for :steps do |step| %>
                                <div class="field">
                                    <%= render "step_fields", f: step %>
                                </div>
                            <% end %>
                            <div class="links">
                                <%= link_to_add_association "Add Step",f, :steps, class: "step-btn" %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</body>

app/views/recipes/from_draft.html.erb
<div class="nav">
    <%= link_to "Cookcare", recipes_path, class: "title" %>
    <%= form_with(url: search_recipes_path, local: true, method: :get) do |f| %>
        <%= f.submit "Search", class: "new-btn" %>
        <%= f.text_field :search, placeholder: "Search Recipes", class: "search-blank" %>
    <% end %>
</div>
<div class="recipe-wrapper clearfix">
    <div class="side-container">
        <%= render template: "layouts/sidecontainer.html.erb" %>
    </div>
    <div class="main-container">
        <% @recipes.each do |recipe| %>
            <div class="index-single clearfix">
                <% if recipe.recipe_image? %>
                    <%= image_tag recipe.recipe_image.url, class: "index-single-image" %>
                <% else %>
                    <%= image_tag "no_image.jpg", class: "index-single-image" %>
                <% end %>
                <div class="index-single-name">
                    <%= link_to recipe.title, recipe_path(recipe), class: "index-single-title" %>
                    <div class="index-single-info clearifix">
                        <div class="index-single-favorite">
                            <%= "Favorites: " + recipe.favorite_users.count.to_s %>
                        </div>
                        <div class="index-single-username">
                            <%= "By " + recipe.user.name %>
                        </div>
                        
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/recipes/index.html.erb
<div class="nav">
    <%= link_to "Cookcare", recipes_path, class: "title" %>
    <%= form_with(url: search_recipes_path, local: true, method: :get) do |f| %>
        <%= f.submit "Search", class: "new-btn" %>
        <%= f.text_field :search, placeholder: "Search Recipes", class: "search-blank" %>
    <% end %>
</div>
<div class="recipe-wrapper clearfix">
    <div class="side-container">
        <%= form_for :session, url: logout_path, method: :delete do |f| %>
            <%= f.submit 'Log Out', class: 'logout-btn' %>
        <% end %>
        <%= render template: "layouts/sidecontainer.html.erb" %>
    </div>
    <div class="main-container">
        <% @recipes.each do |recipe| %>
            <div class="index-single clearfix">
                <% if recipe.recipe_image? %>
                    <%= image_tag recipe.recipe_image.url, class: "index-single-image" %>
                <% else %>
                    <%= image_tag "no_image.jpg", class: "index-single-image" %>
                <% end %>
                <div class="index-single-name">
                    <%= link_to recipe.title, recipe_path(recipe), class: "index-single-title" %>
                    <div class="index-single-info clearifix">
                        <div class="index-single-favorite">
                            <%= "Favorites: " + recipe.favorites.count.to_s %>
                        </div>
                        <div class="index-single-username">
                            <%= "By " + recipe.user.name %>
                        </div>
                        
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/recipes/new.html.erb
<body>
    <%= form_for(@recipe, url: recipes_path) do |f| %>
        <div class="nav">
            <%= link_to "Cookcare", recipes_path, class: "title" %>
            <%= f.submit "Save", class: "new-btn" %>
            <%= f.select :status, Recipe.statuses.keys.to_a, {}, class: "status-btn" %>
        </div>
        <div class="recipe-wrapper clearfix">
            <div class="side-container">
                <%= render template: "layouts/sidecontainer.html.erb" %>
            </div>
            <div class="main-container">
                <div class="recipe-section clearfix">
                    <div class="recipe-left-section">
                        <div class="title-box">
                            <p>Title</p>
                            <%= f.text_field :title, class: "title-blank" %>
                        </div>
                        <div class="category-box">
                            <p>Category</p>
                            <div class="category-blank">
                                <%= f.collection_check_boxes :category_ids, Category.all, :id, :name, include_hidden: false do |b| %>
                                    <%= b.label { b.check_box + b.text } %>
                                <% end %>
                            </div>
                        </div>
                        <div class="ingredient-box">
                            <p>Ingredients</p>
                            <%= f.fields_for :recipe_ingredients do |recipe_ingredient| %>
                                <div class="field">
                                    <%= render "recipe_ingredient_fields", f: recipe_ingredient %>
                                </div>
                            <% end %>
                            <div class="links">
                                <%= link_to_add_association "Add Ingredient",f, :recipe_ingredients, class: "ingredient-btn" %>
                            </div>
                        </div>
                    </div>
                    <div class="recipe-right-section">
                        <%= f.file_field :recipe_image, placeholder: "Photos", class: "photo-box" %>
                        
                        <div class="step-box">
                            <p>Steps</p>
                            <%= f.fields_for :steps do |step| %>
                                <div class="field">
                                    <%= render "step_fields", f: step %>
                                </div>
                            <% end %>
                            <div class="links">
                                <%= link_to_add_association "Add Step",f, :steps, class: "step-btn" %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</body>

app/views/recipes/published.html.erb
<div class="nav">
    <%= link_to "Cookcare", recipes_path, class: "title" %>
    <%= form_with(url: search_recipes_path, local: true, method: :get) do |f| %>
        <%= f.submit "Search", class: "new-btn" %>
        <%= f.text_field :search, placeholder: "Search Recipes", class: "search-blank" %>
    <% end %>
</div>
<div class="recipe-wrapper clearfix">
    <div class="side-container">
        <%= render template: "layouts/sidecontainer.html.erb" %>
    </div>
    <div class="main-container">
        <% @recipes.each do |recipe| %>
            <div class="index-single clearfix">
                <% if recipe.recipe_image? %>
                    <%= image_tag recipe.recipe_image.url, class: "index-single-image" %>
                <% else %>
                    <%= image_tag "no_image.jpg", class: "index-single-image" %>
                <% end %>
                <div class="index-single-name">
                    <%= link_to recipe.title, recipe_path(recipe), class: "index-single-title" %>
                    <div class="index-single-info clearifix">
                        <div class="index-single-favorite">
                            <%= "Favorites: " + recipe.favorite_users.count.to_s %>
                        </div>
                        <div class="index-single-username">
                            <%= "By " + recipe.user.name %>
                        </div>
                        
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/recipes/search.html.erb
<div class="nav">
    <%= link_to "Cookcare", recipes_path, class: "title" %>
    <%= form_with(url: search_recipes_path, local: true, method: :get) do |f| %>
        <%= f.submit "Search", class: "new-btn" %>
        <%= f.text_field :search, placeholder: "Search Recipes", class: "search-blank" %>
    <% end %>
</div>
<div class="recipe-wrapper clearfix">
    <div class="side-container">
        <div class="account-section">
            <div class="account-info-section clearfix">
                <%= image_tag "icon.png", class: "create-image" %>
                <div class="name-link"><%= @current_user.name %> </div>
            </div>
            <div class="user-tag-section">
                <%= link_to edit_user_path(@current_user) do %><span class="tag-link">Edit Profile</span><span class="hover">プロフィール編集</span><% end %>
            </div>
        </div>
        <div class="post-recipe-section">
            <div class="recipe-info-section clearfix">
                <%= image_tag "green_pen.png", class: "create-image" %>
                <div class="name-link">Post Recipe</div>
            </div>
            <div class="recipe-tag-section">
                <%= link_to new_recipe_path do %><span class="tag-link">Create NEW</span><span class="hover">新規投稿</span><% end %><br>
                <%= link_to recipes_from_draft_path do %><span class="tag-link">From Draft</span><span class="hover">一時保存から</span><% end %>
            </div>
        </div>
        <div class="list-section">
            <div class="list-info-section clearfix">
                <%= image_tag "green_list.png", class: "list-image" %>
                <div class="name-link">Your Lists</div>
            </div>
            <div class="list-links">
                <%= link_to recipes_published_path do %><span class="list-link">Published</span><span class="hover">投稿済み</span><% end %><br>
                <%= link_to favorites_index_path do %><span class="list-link">Favorites</span><span class="hover">お気に入り</span><% end %><br>
                <%= link_to favorites_cooked_path do %><span class="list-link">Cooked</span><span class="hover">調理済み</span><% end %><br>
            </div>
            
        </div>
        <div class="diet-section clearfix">
                <%= image_tag "green_calendar.png", class: "create-image" %>
                <%= link_to diets_path do %><span class="name-link">Calendar</span><span class="hover">カレンダー</span><% end %><br>
        </div>
    </div>
    <div class="main-container">
        <% @recipes.each do |recipe| %>
            <div class="index-single clearfix">
                <% if recipe.recipe_image? %>
                    <%= image_tag recipe.recipe_image.url, class: "index-single-image" %>
                <% else %>
                    <%= image_tag "no_image.jpg", class: "index-single-image" %>
                <% end %>
                <div class="index-single-name">
                    <%= link_to recipe.title, recipe_path(recipe), class: "index-single-title" %>
                    <div class="index-single-info clearifix">
                        <div class="index-single-favorite">
                            <%= "Favorites: " + recipe.favorites.favorite.count.to_s %>
                        </div>
                        <div class="index-single-username">
                            <%= "By " + recipe.user.name %>
                        </div>
                        
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/recipes/show.html.erb
<body>
    <%= form_for [@recipe, @memo], url: recipe_memos_path(@recipe), method: :post do |f| %>
        <div class="nav">
            <%= link_to "Cookcare", recipes_path, class: "title" %>
            <% unless @recipe.user_id == @current_user.id %>
                <% if !@recipe.favorite_users.include?(current_user) %>
                    <%= link_to "お気に入り登録", recipe_favorites_path(recipe_id: @recipe.id), {method: :post, class: "favorite-btn"} %>
                <% else %>
                    <%= link_to "お気に入り解除", recipe_favorites_path(recipe_id: @recipe.id), {method: :delete, class: "favorite-btn"} %>
                <% end %>
            <% else %>
                <%= link_to "Edit", edit_recipe_path, {class: "new-btn"} %>
            <% end %>
            <%= f.submit "カレンダーに記録", class: "date-btn" %>
            <%= f.date_field :start_time, value: Time.now.strftime("%Y-%m-%d"), class: "date-btn" %>
        </div>
        <div class="recipe-wrapper clearfix">
            <div class="side-container">
                <%= render template: "layouts/sidecontainer.html.erb" %>
            </div>
            <div class="main-container">
                <div class="recipe-section clearfix">
                    <div class="recipe-left-section clearfix">
                        <div class="show-title-box">
                            <p>Title</p>
                            <div class="show-title">
                                <%= @recipe.title %>
                            </div>
                        </div>
                        <div class="show-username-box">
                            <p>Username</p>
                            <div class="show-username">
                                <%= @recipe.user.name%>
                            </div>
                        </div>
                        <div class="info-box clearfix">
                            <div class="image-box">
                                <p class="show-image-text">Photo</p>
                                <% if @recipe.recipe_image? %>
                                    <%= image_tag @recipe.recipe_image.url, class: "show-image" %>
                                <% else %>
                                    <%= image_tag "no_image.jpg", class: "show-image" %>
                                <% end %>
                            </div>
                            <% if @recipe.memo_users.include?(@current_user) %>
                                <div class="memo-box">
                                    <p>Memo</p>
                                    <%= f.text_area :memo, :value => @memo_recipe.memo, class: "memo-blank" %>
                                </div>
                            <% else %>
                                <div class="memo-box">
                                    <p>Memo</p>
                                    <%= f.text_area :memo, class: "memo-blank" %>
                                </div>
                            <% end %>
                        </div>
                        <div class="show-ingredients-box clearfix">
                            <p>Ingredients</p>
                            <% @recipe_ingredients.each do |recipe_ingredient| %>
                                <div class="show-ingredient">
                                    <%= recipe_ingredient.ingredient.name %>
                                </div>
                                <div class="show-quantity">
                                    <%= recipe_ingredient.quantity %>
                                </div>
                            <% end %>
                        </div>
                    </div>
                    
                    <div class="recipe-right-section">
                        <div class="category-box">
                            <p>Category</p>
                            <% a = 0 %>
                            <% @categories.each do |category1| %>
                                <% @recipe_categories.each do |recipe_category| %>
                                    <% if category1.name == recipe_category.category.name %>
                                        <div class="show-category-on">
                                            <%= category1.name %>
                                            <% a += 1 %>
                                        </div>
                                    <% end %>
                                <% end %>
                                <% if a == 0 %>
                                    <div class="show-category-off">
                                        <%= category1.name %>
                                    </div>
                                <% end %>
                                <% a = 0 %>
                            <% end %>
                        </div>
                        <div class="step-box">
                            <p>Steps</p>
                            <% @steps.each do |step| %>
                                <div class="show-step">
                                    <%= step.step %>
                                </div>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
<body>
    