config/routes.rb
Rails.application.routes.draw do
  get 'memos/index'
	root 'home#index'
	get 'sessions/new'
	
	get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'

	resources :users
	get 'favorites/index', to: 'favorites#index'
	get 'recipes/published', to: 'recipes#published'
	get 'recipes/from_draft', to: 'recipes#from_draft'
	resources :recipes do 
		resource :favorites, only: [:create, :destroy]
		resource :memos, only: [:create]		
		collection do
			get 'search'
		end
	end

	resources :ingredients do
		get :autocomplete_ingredient_name, on: :collection
	end
	
	resources :diets
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    
    has_many :recipe_categories
    has_many :recipes, through: :recipe_categories
    
    has_many :category_diets
    has_many :diets, through: :category_diets
    accepts_nested_attributes_for :category_diets, allow_destroy: true
    
    # CSV.foreach('db/category_data.csv') do |row|
    #     Category.create(:id => row[0], :name => row[1])
    # end
end

app/models/category_diet.rb
class CategoryDiet < ApplicationRecord
    
    belongs_to :category
    belongs_to :diet
end

app/models/check.rb
class Check < ApplicationRecord

	belongs_to :user
	belongs_to :recipe

	enum status: { cooked: 0, favorite: 1, not_favorite: 2 }
	validates :status, inclusion: { in: Favorite.statuses.keys }
	
	class << self
	def localed_statuses
		statuses.keys.map do |s|
			[ApplicationController.helpers.t("status.favorite.#{s}"), s]
		end
	end
	end
	
end

app/models/diet.rb
class Diet < ApplicationRecord
    
    has_many :category_diets
    has_many :categories, through: :category_diets
    accepts_nested_attributes_for :category_diets, allow_destroy: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
  
  validates_uniqueness_of :recipe_id, scope: :user_id
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    # #前方一致検索
    # scope :by_name_like, lambda { |name|
    #     where('name LIKE :value', { value: "#{sanitize_sql_like(name)}%"})
    # }
    
    validates :name, presence: true, length: {maximum: 15}
    
    NESTED_ALLOWED_PARAMS = [:id, :_destroy, :name ]
    has_many :recipe_ingredients, dependent: :destroy
    has_many :recipes, through: :recipe_ingredients
    
    # #uniqueエラーでた。最初のみ使える?
    # #csvファイルを扱うためのgemを読み込む
    # CSV.foreach('db/ingredient_data.csv') do |row|
    # #foreachは、ファイル（hoge.csv）の各行を引数として、ブロック(do~endまでを範囲とする『引数のかたまり』)を繰り返し実行する
    # #rowには、読み込まれた行が代入される
    #     Ingredient.create(:id => row[0], :name => row[1])
    #     #usersテーブルの各カラムに、各行のn番目の値を代入している。
    # end
end

app/models/memo.rb
class Memo < ApplicationRecord
    
    belongs_to :user
	belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    
    mount_uploader :recipe_image, RecipeImageUploader
    
    ALLOWED_PARAMS = [:title, :user_id, :recipe_image, :status, {category_ids: []}, {ingredient_ids: []}]
   
    validates :title, presence: true, length: {maximum: 20}
    
    enum status: { draft: 0, published: 1 }
    validates :status, inclusion: { in: Recipe.statuses.keys }
    

    belongs_to :user
    
    has_many :recipe_ingredients
    has_many :ingredients, through: :recipe_ingredients, dependent: :destroy
    accepts_nested_attributes_for :recipe_ingredients, allow_destroy: true
    # accepts_nested_attributes_for :ingredients
    
    has_many :recipe_categories
    has_many :categories, through: :recipe_categories, dependent: :destroy
    accepts_nested_attributes_for :recipe_categories, allow_destroy: true
    # accepts_nested_attributes_for :categories
    
    has_many :steps
    accepts_nested_attributes_for :steps, allow_destroy: true
    
    has_many :favorites
    has_many :favorite_users, through: :favorites, source: 'user', dependent: :destroy
    
    has_many :memos
    has_many :memo_users, through: :memos, source: 'user', dependent: :destroy
    
end

app/models/recipe_category.rb
class RecipeCategory < ApplicationRecord
	belongs_to :recipe
	belongs_to :category
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
    
    NESTED_ALLOWED_PARAMS = [ :id, :_destroy, :quantity, :recipe_id, :ingredient_id, ingredient_attributes: Ingredient::NESTED_ALLOWED_PARAMS ]
    
    # has_many :recipes
    # has_many :ingredients
    belongs_to :recipe
    belongs_to :ingredient
end

app/models/step.rb
class Step < ApplicationRecord
    NESTED_ALLOWED_PARAMS = [:id, :_destroy, :recipe_id, :step]
    
    validates :step, presence: true, length: {maximum: 30}
    belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
    
    #emailが~@~.~の正規表示
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    
    #passwordが半角英数字最低1文字以上、かつ、8文字以上12文字以下の正規表示
    VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,12}+\z/i
    
    has_secure_password
    validates :name, presence: true, length: {maximum: 15}
    validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}
    validates :password, presence: true, format: {with: VALID_PASSWORD_REGEX}
    
    has_many :recipes
    
    has_many :favorites
    has_many :favorite_recipes, through: :favorites, source: 'recipe'
    
    has_many :memos
    has_many :memo_recipes, through: :memos, source: 'recipe'
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diets_helper.rb
module DietsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<body>
    <div class="top-wrapper clearfix">
        <div class="left-container">
            <div class="left-text">
                <p>Search for your dishes</p>
                <p>Share your recipes</p>
                <p>Record your eating habits</p>
            </div>
        </div>
        
        <div class="right-container">
            <div class="login clearfix">
                <%= form_for :session, url: login_path do |f| %>
                    <div class="login-info">
                        <%= f.label :email %>
                        <%= f.text_field :email, class: "blank" %>
                    </div>
                    <div class="login-info">
                        <%= f.label :password %><br>
                        <%= f.password_field :password, class: "blank", placeholder: "8文字以上12文字以下の英数混合" %>
                    </div>
                    <div class="btn-section">
                        <%= f.submit 'Log in', class: 'mini-btn' %>
                    </div>
                <% end %>
            </div>
            
            <div class="greeting">
                <p>Welcome to Cookcare</p>
            </div>
            <div class="home-image clearfix">
                <div class="left-home-container top-container">
                    <div class="home-info clearfix">
                        <%= image_tag "green_pen.png", class: "home-icon" %>
                        <div class="home-container-text">レシピ投稿機能</div>
                    </div>
                    <div class="home-contents">
                        レシピを投稿することで<br>
                        自分だけのレシピ本を<br>
                        つくることができます<br>
                    </div>
                </div>
                <div class="right-home-container top-container">
                    <div class="home-info clearfix">
                        <%= image_tag "green_search.png", class: "home-icon" %>
                        <div class="home-container-text">レシピ検索機能</div>
                    </div>
                    <div class="home-contents">
                        冷蔵庫にある材料、<br>
                        食べたい料理名で<br>
                        レシピ検索が可能です
                    </div>
                </div>
                <div class="left-home-container">
                    <div class="home-info clearfix">
                        <%= image_tag "green_memo.png", class: "home-icon" %>
                        <div class="home-container-text">アレンジ機能</div>
                    </div>
                    <div class="home-contents">
                        参考にしたレシピに<br>
                        memo書きすることで<br>
                        自分流にアレンジできます
                    </div>
                </div>
                <div class="right-home-container">
                    <div class="home-info clearfix">
                        <%= image_tag "green_calendar.png", class: "home-icon" %>
                        <div class="home-container-text">食生活管理機能</div>
                    </div>
                    <div class="home-contents">
                        cookedボタンにより作った料理を<br>
                        カレンダーに反映でき、<br>
                        日々の食事を記録できます<br>
                        
                        
                    </div>
                </div>
            </div>
            <div class="account-section">
                <p>Cookcareをはじめよう</p>
                <%= link_to 'Create an Account', new_user_path, class: "btn" %>
                <%= link_to 'Log In', sessions_new_path, class: "btn" %>
            </div>
        </div>
    </div>
</body>