config/routes.rb
Rails.application.routes.draw do
  get 'memos/index'
	root 'home#index'
	get 'sessions/new'
	
	get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'

	resources :users
	get 'favorites/index', to: 'favorites#index'
	get 'recipes/published', to: 'recipes#published'
	get 'recipes/from_draft', to: 'recipes#from_draft'
	resources :recipes do 
		resource :favorites, only: [:create, :destroy]
		resource :memos, only: [:create]		
		collection do
			get 'search'
		end
	end

	resources :ingredients do
		get :autocomplete_ingredient_name, on: :collection
	end
	
	resources :diets
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    
    has_many :recipe_categories
    has_many :recipes, through: :recipe_categories
    
    has_many :category_diets
    has_many :diets, through: :category_diets
    accepts_nested_attributes_for :category_diets, allow_destroy: true
    
    # CSV.foreach('db/category_data.csv') do |row|
    #     Category.create(:id => row[0], :name => row[1])
    # end
end

app/models/category_diet.rb
class CategoryDiet < ApplicationRecord
    
    belongs_to :category
    belongs_to :diet
end

app/models/check.rb
class Check < ApplicationRecord

	belongs_to :user
	belongs_to :recipe

	enum status: { cooked: 0, favorite: 1, not_favorite: 2 }
	validates :status, inclusion: { in: Favorite.statuses.keys }
	
	class << self
	def localed_statuses
		statuses.keys.map do |s|
			[ApplicationController.helpers.t("status.favorite.#{s}"), s]
		end
	end
	end
	
end

app/models/diet.rb
class Diet < ApplicationRecord
    
    has_many :category_diets
    has_many :categories, through: :category_diets
    accepts_nested_attributes_for :category_diets, allow_destroy: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
  
  validates_uniqueness_of :recipe_id, scope: :user_id
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    # #前方一致検索
    # scope :by_name_like, lambda { |name|
    #     where('name LIKE :value', { value: "#{sanitize_sql_like(name)}%"})
    # }
    
    validates :name, presence: true, length: {maximum: 15}
    
    NESTED_ALLOWED_PARAMS = [:id, :_destroy, :name ]
    has_many :recipe_ingredients, dependent: :destroy
    has_many :recipes, through: :recipe_ingredients
    
    # #uniqueエラーでた。最初のみ使える?
    # #csvファイルを扱うためのgemを読み込む
    # CSV.foreach('db/ingredient_data.csv') do |row|
    # #foreachは、ファイル（hoge.csv）の各行を引数として、ブロック(do~endまでを範囲とする『引数のかたまり』)を繰り返し実行する
    # #rowには、読み込まれた行が代入される
    #     Ingredient.create(:id => row[0], :name => row[1])
    #     #usersテーブルの各カラムに、各行のn番目の値を代入している。
    # end
end

app/models/memo.rb
class Memo < ApplicationRecord
    
    belongs_to :user
	belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    
    mount_uploader :recipe_image, RecipeImageUploader
    
    ALLOWED_PARAMS = [:title, :user_id, :recipe_image, :status, {category_ids: []}, {ingredient_ids: []}]
   
    validates :title, presence: true, length: {maximum: 20}
    
    enum status: { draft: 0, published: 1 }
    validates :status, inclusion: { in: Recipe.statuses.keys }
    

    belongs_to :user
    
    has_many :recipe_ingredients
    has_many :ingredients, through: :recipe_ingredients, dependent: :destroy
    accepts_nested_attributes_for :recipe_ingredients, allow_destroy: true
    # accepts_nested_attributes_for :ingredients
    
    has_many :recipe_categories
    has_many :categories, through: :recipe_categories, dependent: :destroy
    accepts_nested_attributes_for :recipe_categories, allow_destroy: true
    # accepts_nested_attributes_for :categories
    
    has_many :steps
    accepts_nested_attributes_for :steps, allow_destroy: true
    
    has_many :favorites
    has_many :favorite_users, through: :favorites, source: 'user', dependent: :destroy
    
    has_many :memos
    has_many :memo_users, through: :memos, source: 'user', dependent: :destroy
    
end

app/models/recipe_category.rb
class RecipeCategory < ApplicationRecord
	belongs_to :recipe
	belongs_to :category
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
    
    NESTED_ALLOWED_PARAMS = [ :id, :_destroy, :quantity, :recipe_id, :ingredient_id, ingredient_attributes: Ingredient::NESTED_ALLOWED_PARAMS ]
    
    # has_many :recipes
    # has_many :ingredients
    belongs_to :recipe
    belongs_to :ingredient
end

app/models/step.rb
class Step < ApplicationRecord
    NESTED_ALLOWED_PARAMS = [:id, :_destroy, :recipe_id, :step]
    
    validates :step, presence: true, length: {maximum: 30}
    belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
    
    #emailが~@~.~の正規表示
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    
    #passwordが半角英数字最低1文字以上、かつ、8文字以上12文字以下の正規表示
    VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,12}+\z/i
    
    has_secure_password
    validates :name, presence: true, length: {maximum: 15}
    validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}
    validates :password, presence: true, format: {with: VALID_PASSWORD_REGEX}
    
    has_many :recipes
    
    has_many :favorites
    has_many :favorite_recipes, through: :favorites, source: 'recipe'
    
    has_many :memos
    has_many :memo_recipes, through: :memos, source: 'recipe'
    
end

app/controllers/diets_controller.rb
class DietsController < ApplicationController
	
	before_action :authenticate_user
	
	def index
		@diets = Diet.where(user_id: current_user).order(start_time: "desc")
		@diet = Diet.new
		@memos = current_user.memos
		# binding.pry
	end
	
	def create
		@diet = Diet.new(diet_params)
		# binding.pry
		if @diet.save
			redirect_to diets_path, seccess: "記録完了"
		else
			flash[:danger] = "記録失敗"
			render :index
		end
	end
	
	def edit
		@diet = Diet.find_by(id: params[:id])
	end
	
	def update
		@diet = Diet.find(params[:id])
		
		if @diet.update(diet_params)
			redirect_to diets_path
		else
			render :edit
		end
	end
	
	def destroy
		@diet = Diet.find_by(id: params[:id])
		@diet.destroy
		redirect_to diets_path, danger: "記録を削除しました"
	end
	
	private
	def diet_params
		params.require(:diet).permit(:recipe_id, :title, :place, :start_time, category_ids: [], category_diets_attributes: [:category_id]).merge(user_id: current_user.id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diets_helper.rb
module DietsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/diets/edit.html.erb
<div class="nav">
		<%= link_to "Cookcare", recipes_path, class: "title" %>
</div>
<div class="recipe-wrapper clearfix">
    <div class="side-container">
        <div class="account-section">
            <div class="account-info-section clearfix">
                <%= image_tag "icon.png", class: "create-image" %>
                <div class="name-link"><%= @current_user.name %> </div>
            </div>
            <div class="user-tag-section">
                <%= link_to edit_user_path(@current_user) do %><span class="tag-link">Edit Profile</span><span class="hover">プロフィール編集</span><% end %>
            </div>
        </div>
        <div class="post-recipe-section">
            <div class="recipe-info-section clearfix">
                <%= image_tag "green_pen.png", class: "create-image" %>
                <div class="name-link">Post Recipe</div>
            </div>
            <div class="recipe-tag-section">
                <%= link_to new_recipe_path do %><span class="tag-link">Create NEW</span><span class="hover">新規投稿</span><% end %><br>
                <%= link_to recipes_from_draft_path do %><span class="tag-link">From Draft</span><span class="hover">一時保存から</span><% end %>
            </div>
        </div>
        <div class="list-section">
            <div class="list-info-section clearfix">
                <%= image_tag "green_list.png", class: "list-image" %>
                <div class="name-link">Your Lists</div>
            </div>
            <div class="list-links">
                <%= link_to recipes_published_path do %><span class="list-link">Published</span><span class="hover">投稿済み</span><% end %><br>
                <%= link_to favorites_index_path do %><span class="list-link">Favorites</span><span class="hover">お気に入り</span><% end %><br>
                <%= link_to favorites_cooked_path do %><span class="list-link">Cooked</span><span class="hover">調理済み</span><% end %><br>
            </div>
            
        </div>
        <div class="diet-section clearfix">
                <%= image_tag "green_calendar.png", class: "create-image" %>
                <%= link_to diets_path do %><span class="name-link">Calendar</span><span class="hover">カレンダー</span><% end %><br>
        </div>
    </div>
	<div class="main-container">
		<div class="diet-index-section">
			<div class="edit-diet-section">
				<%= form_for @diet do |f| %>
					<%= f.text_field :title, placeholder: "Title", class: "record-blank" %>
					<%= f.text_field :place, placeholder: "Place", class: "record-blank" %>
					<%= f.date_field :start_time, class: "record-btn" %><br>
					<%= f.collection_check_boxes :category_ids, Category.all, :id, :name, include_hidden: false do |b| %>
						<%= b.label { b.check_box + b.text } %>
					<% end %>
					<%= f.submit "Update", class: "record-save-btn" %>
					<%= link_to "Delete", diet_path(@diet.id), {method: :delete, class: "record-delete-btn"} %><br>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/diets/index.html.erb
<div class="nav">
		<%= link_to "Cookcare", recipes_path, class: "title" %>
</div>
<div class="recipe-wrapper clearfix">
    <div class="side-container">
    	<%= render template: "layouts/sidecontainer.html.erb" %>
    </div>
	<div class="main-container">
		<div class="diet-index-section">
			<div class="top-diet-section">
				<%= form_for @diet do |f| %>
					<%= f.text_field :title, placeholder: "Title", class: "record-blank" %>
					<%= f.text_field :place, placeholder: "Place", class: "record-blank" %>
					<%= f.date_field :start_time, value: Time.now.strftime("%Y-%m-%d"), class: "record-btn" %>
					<%= f.submit "Save", class: "record-save-btn" %><br>
					<%= f.collection_check_boxes :category_ids, Category.all, :id, :name, include_hidden: false do |b| %>
						<%= b.label { b.check_box + b.text } %>
					<% end %>
				<% end %>
			</div>
			<div class="bottom-diet-section">
				<%= month_calendar events: @diets do |date, diets| %>
					<%= date.day %><br>
					
					<% diets.each do |diet| %>
						<%= link_to "・" + diet.title, "/diets/#{diet.id}/edit" %><br>
					<% end %>
					<% @memos.each do |memo| %>
						<% if memo.start_time == date %>
							<%= link_to "・" + memo.recipe.title, "/recipes/#{memo.recipe.id}" %><br>
							<!--<% memo.recipe.categories.each do |category| %>-->
							<!--	<div class="show-category-on">-->
							<!--		<%= category.name %>-->
							<!--	</div>-->
							<!--<% end %>-->
						<% end %>
					<% end %>
				<% end %>
			</div>
		</div>
	</div>
</div>